from enum import StrEnum


class ErrorCode(StrEnum):
    UNAUTHORIZED = "UNAUTHORIZED"
    INVALID_TOKEN = "INVALID_TOKEN"
    INVALID_USER = "INVALID_USER"

    EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    VERIFICATION_CODE_NOT_FOUND = "VERIFICATION_CODE_NOT_FOUND"
    VERIFICATION_CODE_EXPIRED = "VERIFICATION_CODE_EXPIRED"
    INVALID_VERIFICATION_CODE = "INVALID_VERIFICATION_CODE"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    UNSUPPORTED_AUTH_FLOW = "UNSUPPORTED_AUTH_FLOW"
    INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN"
    DEVICE_MISMATCH = "DEVICE_MISMATCH"
    REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED"
    EMAIL_SEND_FAILED = "EMAIL_SEND_FAILED"
    SERVER_MISCONFIGURED = "SERVER_MISCONFIGURED"
    TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS"

    COURSE_NOT_FOUND = "COURSE_NOT_FOUND"
    COURSE_ACCESS_DENIED = "COURSE_ACCESS_DENIED"
    CHAPTER_NOT_FOUND = "CHAPTER_NOT_FOUND"

    VALIDATION_ERROR = "VALIDATION_ERROR"

    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    SESSION_ACCESS_DENIED = "SESSION_ACCESS_DENIED"
    QUOTA_EXCEEDED = "QUOTA_EXCEEDED"
    BUG_REPORT_NOT_FOUND = "BUG_REPORT_NOT_FOUND"
